### ISSUE TITLE
Scrambled start / menu screen

### ISSUE THREAD

**Issue by blogmywiki** [Smashcat/UNO_Manic_Miner#1]
Hi there - I love the project! I posted this on YouTube, thought an image might be useful.

I built the project using a breadboard and have buttons and sound working - and video, except on the menu screen.

I've swapped the resistor values to the latest ones, and I'm getting the same results: the menu screen is badly garbled as if there's something wrong with the code / compilation. I can see where the menu highlight bar is, and move it down, but there's no readable text, just (crisp) patterns of dots. The level screens all seem to show ok though. All I did to the code was delete the debug file and the reference to it, to make it small enough to compile. My Arduino is an old but genuine Uno - and the game is mostly working!

![IMG_6610](https://github.com/Smashcat/UNO_Manic_Miner/assets/6705905/c2bedef0-8b2f-4e0f-9dd7-b4e21389c1f1)
![IMG_6606 copy](https://github.com/Smashcat/UNO_Manic_Miner/assets/6705905/c09f3442-5221-4b5c-b5ae-0f48418cd212)

**Comment by Smashcat** [comment]
Thanks, I saw your post and replied on YouTube, but probably better to keep the convo here I think. It definitely looks like a memory issue, as the sprites are also in the wrong place. Is your Arduino UNO an ATMega328P - based board? It seems like the graphical data at the top end of memory is missing or corrupted. If you can tell me the revision of the board you have then I can investigate :) Also, are you using the latest version of Arduino to compile?

**Comment by blogmywiki** [comment]
It's an Arduino UNO SMD R2 which according to https://support.arduino.cc/hc/en-us/articles/7901453165724-An-overview-of-different-UNO-boards is based on the ATmega328P. 

I updated the Arduino IDE just before compiling, I'm on version 2.3.2

Also, the game does seem playable, I can make progress at least on level 1 and score points!

**Comment by Smashcat** [comment]
Ok that's good that some of it is working at least! I'm going to try sourcing an R2. I have an R3 here, and am getting an SMD R3 to test also. They should all use the same microcontroller though, so I'm wondering if it is the bootloader. When you compile the sketch does it report the following for you? 

Sketch uses 32252 bytes (99%) of program storage space. Maximum is 32256 bytes.
Global variables use 1888 bytes (92%) of dynamic memory, leaving 160 bytes for local variables. Maximum is 2048 bytes.

**Comment by blogmywiki** [comment]
Thanks for this! The compile message, having removed debug.h, is:
```
Sketch uses 31422 bytes (97%) of program storage space. Maximum is 32256 bytes.
Global variables use 1696 bytes (82%) of dynamic memory, leaving 352 bytes for local variables. Maximum is 2048 bytes.
```

It won't compile with debug.h present, I get this message:
```
Sketch uses 32278 bytes (100%) of program storage space. Maximum is 32256 bytes.
Global variables use 1888 bytes (92%) of dynamic memory, leaving 160 bytes for local variables. Maximum is 2048 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board
Compilation error: text section exceeds available space in board
```

I wonder if I have the wrong programmer selected and that's the cause? (I don't really understand what the programmer is!)

**Comment by Smashcat** [comment]
Ah! I've just removed debug.h here and see the same decrease in memory usage. It's weird as those functions are not used. Now I'm seeing the same issue you can see. I think I know what it is - watch this space!

**Comment by Smashcat** [comment]
I have reduced the code size slightly, so it should compile for you with debug.h included now. Been discussing with the Arduino devs and apparently Serial.print() is treated in a "special" way, and always results in additional code, even if not used! For some reason some alignment was being broken when Serial.print() was not included, so I've left it in for now! Please let me know if it fixes things.

**Comment by blogmywiki** [comment]
That's fixed it! Thank you so much.
